version: 0.2

env:
  secrets-manager:
    SSHPASSTMP: ec2PasswordSecret:ec2Password

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo "Starting docker daemon..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      # - echo Build started on `date`
      # - docker build -t 108607216059.dkr.ecr.eu-west-2.amazonaws.com/vpc-test:latest . -f ./Dockerfile
  post_build:
    commands:
      # - echo Pushing image to ECR...
      # - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 108607216059.dkr.ecr.eu-west-2.amazonaws.com
      # - docker push 108607216059.dkr.ecr.eu-west-2.amazonaws.com/vpc-test:latest
      - echo Rebooting EC2
      - yum -y install sshpass
      - export SSHPASS=$SSHPASSTMP
      - echo $SSHPASS
      - sshpass -e ssh ubuntu@ec2-18-130-102-119.eu-west-2.compute.amazonaws.com 'sudo systemctl restart hello.service'
